language: c

matrix:
  include:
  - os: osx
    env: BUILD_ENV=darwin_x64


  - env: BUILD_ENV=linux_x64
    sudo: true


# install:
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
#       if [[ "$ENABLE_DOCS" != "" ]]; then
#         sudo apt-get update;
#         sudo apt-get install python3.4;
#         sudo ln -s -f /usr/bin/python3.4 /usr/bin/python;
#         sudo apt-get install doxygen  graphviz;
#         curl -L -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py;
#         sudo python /tmp/get-pip.py;
#         sudo pip install breathe;
#         sudo pip install -U sphinx;
#       fi

#       if [[ "$ANDROID_ABI" == "" ]]; then
#         if [[ "$RASPBERRRIPI" != "" ]]; then
#           cd /tmp && git clone https://github.com/raspberrypi/tools.git raspberrypitools;
#           export RPI_TOOLCHAIN_HOME=/tmp/raspberrypitools;
#           cd /tmp && wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz;
#           tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz;
#           export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH;
#         fi
#       else
#         echo y | sdkmanager 'ndk-bundle';
#         export ANDROID_NDK_HOME=/usr/local/android-sdk/ndk-bundle;
#         cd /tmp && wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz;
#         tar -xzvf cmake-3.11.4-Linux-x86_64.tar.gz;
#         export PATH=/tmp/cmake-3.11.4-Linux-x86_64/bin:$PATH;
#       fi
#     fi

script:
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && mkdir $BUILD_ENV && cd $BUILD_ENV
  - cmake -DCMAKE_INSTALL_PREFIX=dist ../..
  - make && make install
  - ./dist/bin/elacrawler -c ../../src/elacrawler.conf -v 7 -l 20